// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gylemjegmangxyqzxhas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5bGVtamVnbWFuZ3h5cXp4aGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjM2NTUsImV4cCI6MjA2MDE5OTY1NX0.W5hv0fSJ6u4Q3RLoE5SF6H3MWmMsz7FUtknT3CYgJLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);